import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
<html lang="en">
  <body
    className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
  >
    <section className="min-h-screen flex flex-col">

      {/* HEADER */}
      <nav className="sticky top-0 z-50 w-full bg-background/80 backdrop-blur-md border-b border-foreground/10">
        <div className="max-w-5xl mx-auto flex items-center justify-between py-4 px-6">

          {/* Logo / Title */}
          <Link
            href="/"
            className="text-lg font-semibold tracking-wide hover:text-blue-500 transition-colors"
          >
            EMPLOYEE REGISTRY
          </Link>

          {/* Navigation Links */}
          <div className="flex gap-6 text-sm">
            <Link
              href="/login"
              className="hover:text-blue-500 transition-colors"
            >
              Login
            </Link>

            <Link
              href="/logout"
              className="hover:text-red-500 transition-colors"
            >
              Logout
            </Link>
          </div>

        </div>
      </nav>

      {/* PAGE CONTENT */}
      <main className="flex-1">
        {children}
      </main>

    </section>
  </body>
</html>
  );
}
